name: Update Shabbat Times

on:
  schedule:
    # Run every Wednesday and Friday at 08:00 UTC
    - cron: '0 8 * * 3,5'
  workflow_dispatch: # Allows you to click a button to run it manually

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python scrape.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Shabbat times" && git push)